"tests":
    "HTTP Requests should be limited to 1 per page":
        path: "/.*"
        assertions:
            - "metrics.http.requests.count <= 1"

scenarios: |
    #!blackfire-player

    scenario
        name "Basic Visit"

        visit url('/')
            name "Homepage"
            expect status_code() == 200
            expect css("tbody.js-sightings-list tr").count() > 10
            assert metrics.sql.queries.count < 30
            assert main.wall_time < 100ms

        click link("Log In")
            name "Log in page"
            expect status_code() == 200
